export const MOCK = {
  tbbt: {
    events: [
      {
        id: 1,
        title: "Annual Media Summit 2026",
        date: "2026-05-15",
        venue: "The Grand Hall, Delhi",
        status: "upcoming",
        tickets: 450,
        capacity: 600,
      },
      {
        id: 2,
        title: "Creator Economy Meetup",
        date: "2026-04-02",
        venue: "WeWork BKC, Mumbai",
        status: "upcoming",
        tickets: 120,
        capacity: 200,
      },
      {
        id: 3,
        title: "Brand Storytelling Workshop",
        date: "2026-02-18",
        venue: "IHC, New Delhi",
        status: "completed",
        tickets: 85,
        capacity: 100,
      },
    ],
    blog: [
      {
        id: 1,
        title: "The Future of Experiential Marketing",
        status: "published",
        date: "2026-03-10",
        author: "Arjun Mehta",
        views: 1240,
      },
      {
        id: 2,
        title: "How We Planned a 5000-Pax Event in 30 Days",
        status: "draft",
        date: "2026-03-18",
        author: "Priya Sharma",
        views: 0,
      },
    ],
    gallery: [
      {
        id: 1,
        name: "Summit 2025 Highlights",
        count: 48,
        cover: "summit-2025.jpg",
      },
      { id: 2, name: "Behind the Scenes", count: 24, cover: "bts.jpg" },
    ],
  },
  cso: {
    blog: [
      {
        id: 1,
        title: "Science for Every Child: Our 2026 Vision",
        status: "published",
        date: "2026-03-01",
        author: "Dr. Neha Gupta",
        views: 890,
      },
      {
        id: 2,
        title: "Kirby Place School Annual Report",
        status: "published",
        date: "2026-02-15",
        author: "CSO Team",
        views: 1560,
      },
      {
        id: 3,
        title: "Green Innovation Hackathon Recap",
        status: "draft",
        date: "2026-03-20",
        author: "Rahul Verma",
        views: 0,
      },
    ],
    programs: [
      {
        id: 1,
        name: "Kirby Place School",
        status: "active",
        beneficiaries: 340,
        location: "New Delhi",
      },
      {
        id: 2,
        name: "Science Workshops",
        status: "active",
        beneficiaries: 1200,
        location: "Pan-India",
      },
      {
        id: 3,
        name: "Green Tech Initiative",
        status: "planning",
        beneficiaries: 0,
        location: "Delhi NCR",
      },
    ],
    team: [
      {
        id: 1,
        name: "Dr. Neha Gupta",
        role: "Executive Director",
        department: "Leadership",
      },
      {
        id: 2,
        name: "Rahul Verma",
        role: "Program Manager",
        department: "Operations",
      },
      {
        id: 3,
        name: "Sneha Kapoor",
        role: "Outreach Lead",
        department: "Community",
      },
    ],
    donations: {
      total: 2450000,
      thisMonth: 185000,
      donors: 342,
      recurring: 89,
    },
    inquiries: [
      {
        id: 1,
        name: "Amit Singh",
        email: "amit@school.edu",
        type: "Volunteer",
        date: "2026-03-22",
        status: "new",
      },
      {
        id: 2,
        name: "Priya Rao",
        email: "priya@corp.com",
        type: "Partnership",
        date: "2026-03-20",
        status: "replied",
      },
    ],
  },
  nao: {
    experts: [
      {
        id: 1,
        name: "Dr. V.K. Saraswat",
        title: "Member, NITI Aayog",
        category: "Bureaucracy",
        photo: "",
      },
      {
        id: 2,
        name: "Prof. Rajesh Kumar",
        title: "HOD Aerospace, IIT Bombay",
        category: "Academia",
        photo: "",
      },
      {
        id: 3,
        name: "Capt. Meera Nair",
        title: "Chief Pilot, IndiGo",
        category: "Industry",
        photo: "",
      },
      {
        id: 4,
        name: "Dr. Sanjay Gupta",
        title: "Scientist, DRDO",
        category: "Bureaucracy",
        photo: "",
      },
    ],
    resources: [
      {
        id: 1,
        title: "Aviation Fundamentals — Study Guide",
        type: "PDF",
        downloads: 3400,
        status: "published",
      },
      {
        id: 2,
        title: "Practice Test — Phase 1 (Group 1)",
        type: "Quiz",
        downloads: 2100,
        status: "published",
      },
      {
        id: 3,
        title: "Video: How Aircraft Fly",
        type: "Video",
        downloads: 1800,
        status: "published",
      },
      {
        id: 4,
        title: "Phase 2 Question Bank",
        type: "PDF",
        downloads: 0,
        status: "draft",
      },
    ],
    partners: [
      { id: 1, name: "Boeing India", tier: "Title Sponsor", logo: "" },
      { id: 2, name: "Airbus", tier: "Gold Partner", logo: "" },
      { id: 3, name: "HAL", tier: "Silver Partner", logo: "" },
    ],
    registrations: {
      totalSchools: 8420,
      totalStudents: 84200,
      states: 36,
      group1: 52100,
      group2: 32100,
    },
    news: [
      {
        id: 1,
        title: "Vice President Lauds NAO Initiative",
        status: "published",
        date: "2026-03-15",
        views: 4500,
      },
      {
        id: 2,
        title: "Phase 1 Registration Closes August 2026",
        status: "published",
        date: "2026-03-10",
        views: 2200,
      },
    ],
  },
  aeron: {
    products: [
      {
        id: 1,
        name: "Boeing 747 Lapel Pin",
        price: 2499,
        stock: 45,
        status: "active",
        sku: "AER-747-LP",
        image: "",
        category: "Lapel Pins",
      },
      {
        id: 2,
        name: "Spitfire Cufflinks",
        price: 4999,
        stock: 18,
        status: "active",
        sku: "AER-SPT-CL",
        image: "",
        category: "Cufflinks",
      },
      {
        id: 3,
        name: "Cessna 172 Pendant",
        price: 3499,
        stock: 0,
        status: "out_of_stock",
        sku: "AER-C172-PD",
        image: "",
        category: "Pendants",
      },
      {
        id: 4,
        name: "F-16 Tie Bar",
        price: 1999,
        stock: 32,
        status: "active",
        sku: "AER-F16-TB",
        image: "",
        category: "Tie Bars",
      },
      {
        id: 5,
        name: "Airbus A380 Brooch",
        price: 3999,
        stock: 7,
        status: "low_stock",
        sku: "AER-A380-BR",
        image: "",
        category: "Brooches",
      },
    ],
    collections: [
      { id: 1, name: "Military Aviation", count: 12, featured: true },
      { id: 2, name: "Commercial Fleet", count: 8, featured: true },
      { id: 3, name: "Vintage Warbirds", count: 6, featured: false },
    ],
    orders: [
      {
        id: "ORD-1042",
        customer: "Rajat Mehra",
        items: 2,
        total: 7498,
        status: "shipped",
        date: "2026-03-22",
      },
      {
        id: "ORD-1041",
        customer: "Emily Clark",
        items: 1,
        total: 4999,
        status: "processing",
        date: "2026-03-21",
      },
      {
        id: "ORD-1040",
        customer: "Vikram S.",
        items: 3,
        total: 8497,
        status: "delivered",
        date: "2026-03-18",
      },
    ],
    customers: {
      total: 1840,
      returning: 420,
      avgOrder: 3200,
      topCity: "New Delhi",
    },
  },
  avtrade: {
    blog: [
      {
        id: 1,
        title: "Understanding Daily Trade Returns",
        status: "published",
        date: "2026-03-12",
        author: "AV Team",
        views: 680,
      },
      {
        id: 2,
        title: "How Referral Bonuses Work",
        status: "published",
        date: "2026-03-05",
        author: "AV Team",
        views: 1100,
      },
      {
        id: 3,
        title: "Star Rank System Explained",
        status: "draft",
        date: "2026-03-22",
        author: "Admin",
        views: 0,
      },
    ],
    plans: [
      {
        id: 1,
        name: "Starter",
        deposit: 100,
        dailyReturn: "1.2%",
        status: "active",
      },
      {
        id: 2,
        name: "Growth",
        deposit: 500,
        dailyReturn: "1.5%",
        status: "active",
      },
      {
        id: 3,
        name: "Premium",
        deposit: 2000,
        dailyReturn: "1.8%",
        status: "active",
      },
      {
        id: 4,
        name: "Elite",
        deposit: 5000,
        dailyReturn: "2.0%",
        status: "coming_soon",
      },
    ],
    users: {
      total: 12400,
      active: 8200,
      newThisWeek: 340,
      totalDeposits: 4200000,
    },
    analytics: {
      dailyVolume: 84000,
      totalPayouts: 1890000,
      avgDeposit: 340,
      referralRate: 32,
    },
  },
};
