// src/lib/sites.js
export const SITES = {
  tbbt: {
    id: "tbbt",
    name: "TBBT Media",
    domain: "bigbooktheory.com",
    color: "#E84D3D",
    description: "Precision-Engineered Events",
    logo: "TBBT",
    modules: [
      // { id: "dashboard", label: "Dashboard", icon: "home" },
       { id: "blog", label: "Blog Posts", icon: "blog" },
      { id: "events", label: "Events", icon: "event" },
     
      { id: "gallery", label: "Media Gallery", icon: "gallery" },
      { id: "settings", label: "Settings", icon: "settings" },
    ],
  },
  cso: {
    id: "cso",
    name: "CSO India",
    domain: "thecso.in",
    color: "#1A7A4C",
    description: "Centre for Scientific Outreach",
    logo: "CSO",
    modules: [
      // { id: "dashboard", label: "Dashboard", icon: "home" },
      { id: "blog", label: "Blogs", icon: "blog" },
      // { id: "programs", label: "Programs", icon: "award" },
      // { id: "team", label: "Team Members", icon: "people" },
      // { id: "donations", label: "Donations", icon: "donation" },
      // { id: "inquiries", label: "Inquiries", icon: "inbox" },
      // { id: "settings", label: "Settings", icon: "settings" },
    ],
  },
  nao: {
    id: "nao",
    name: "NAO 2026",
    domain: "nao-new.vercel.app",
    color: "#0E4DA4",
    description: "National Aviation Olympiad",
    logo: "NAO",
    modules: [
      // { id: "dashboard", label: "Dashboard", icon: "home" },
       { id: "blog", label: "Blogs", icon: "blog" },
      { id: "experts", label: "Expert Panel", icon: "people" },
      { id: "resources", label: "Resources", icon: "resource" },
      { id: "partners", label: "Partners", icon: "partner" },
      // { id: "registrations", label: "Registrations", icon: "users" },
      // { id: "news", label: "News & Updates", icon: "blog" },
      { id: "settings", label: "Settings", icon: "settings" },
    ],
  },
  // aeron: {
  //   id: "aeron",
  //   name: "Aeron & Co.",
  //   domain: "aircraftlapel.com",
  //   color: "#8B6914",
  //   description: "925 Sterling Silver Aviation Accessories",
  //   logo: "A&C",
  //   modules: [
  //     { id: "dashboard", label: "Dashboard", icon: "home" },
  //     { id: "products", label: "Products", icon: "product" },
  //     { id: "collections", label: "Collections", icon: "gallery" },
  //     { id: "orders", label: "Orders", icon: "order" },
  //     { id: "customers", label: "Customers", icon: "users" },
  //     { id: "settings", label: "Settings", icon: "settings" },
  //   ],
  // },
  // avtrade: {
  //   id: "avtrade",
  //   name: "AV Trade",
  //   domain: "avtrade.in",
  //   color: "#6C3FA0",
  //   description: "Digital Trading Platform",
  //   logo: "AVT",
  //   modules: [
  //     { id: "dashboard", label: "Dashboard", icon: "home" },
  //     { id: "blog", label: "Blog / Content", icon: "blog" },
  //     { id: "plans", label: "Plans & Packages", icon: "dollar" },
  //     { id: "users", label: "User Management", icon: "users" },
  //     { id: "analytics", label: "Analytics", icon: "chart" },
  //     { id: "settings", label: "Settings", icon: "settings" },
  //   ],
  // },
};
